services:
  accounts:
    image: ${IMAGE}
    container_name: accounts
    volumes: &volumes
      - ${HOME}/code/accounts:/app/code/accounts
      - ${HOME}/code/ledger:/app/code/ledger
    labels:
      com.centurylinklabs.watchtower.no-pull: true
      sablier.enable: true
    restart: unless-stopped
    networks:
      - cloudflare

  accounts_hourly:
    image: ${IMAGE}
    profiles: [ "scripts" ]
    container_name: accounts_hourly
    volumes: *volumes
    labels:
      com.centurylinklabs.watchtower.no-pull: true
    command: "/app/code/accounts/finance_hourly.py"

  accounts_daily:
    image: ${IMAGE}
    profiles: [ "scripts" ]
    container_name: accounts_daily
    volumes: *volumes
    labels:
      com.centurylinklabs.watchtower.no-pull: true
    depends_on:
      selenium:
        condition: service_healthy
    command: "/app/code/accounts/finance_daily.py"

  accounts_daily_script:
    image: ${IMAGE}
    profiles: [ "scripts" ]
    container_name: accounts_daily_script
    volumes: *volumes
    labels:
      com.centurylinklabs.watchtower.no-pull: true
    depends_on:
      selenium:
        condition: service_healthy
    command: "/app/code/accounts/${SCRIPT}"

  selenium:
    image: selenium/standalone-chromium
    profiles: [ "scripts" ]
    container_name: selenium
    shm_size: 2g
    environment:
      - SE_ENABLE_TRACING=false
    ports:
      - "7900:7900"
    healthcheck:
      test: &selenium-healthcheck [ "CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444" ]
    labels:
      com.centurylinklabs.watchtower.no-pull: true

  selenium-dev:
    image: selenium/standalone-chromium
    profiles: [ "scripts" ]
    container_name: selenium-dev
    shm_size: 2g
    environment:
      - SE_ENABLE_TRACING=false
    ports:
      - "7901:7900"
      - "4444:4444"
    healthcheck:
      test: *selenium-healthcheck
    labels:
      com.centurylinklabs.watchtower.no-pull: true

networks:
  cloudflare:
    name: cloudflare
    external: true
