services:
  accounts:
    image: accounts_mambaforge:1.2
    container_name: accounts
    user: 1000:1000
    volumes:
      - ${HOME}/code/accounts:/home/valankar/code/accounts
      - ${HOME}/code/ledger:/home/valankar/code/ledger
    labels:
      com.centurylinklabs.watchtower.no-pull: true
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8050/health" ]

networks:
  default:
    name: cloudflare
    external: true
