services:
  accounts: &accounts
    image: ${IMAGE}
    container_name: accounts
    volumes: &volumes
      - ${HOME}/code/accounts:/app/code/accounts
      - ${HOME}/code/ledger:/app/code/ledger
    environment: &environment
      REDIS_HOST: valkey
      ALPHA_VANTAGE_KEY: ${ALPHA_VANTAGE_KEY}
      SCHWAB_API_KEY: ${SCHWAB_API_KEY}
      SCHWAB_SECRET: ${SCHWAB_SECRET}
      SCHWAB_CALLBACK_URI: ${SCHWAB_CALLBACK_URI}
      FRED_API_KEY: ${FRED_API_KEY}
    restart: unless-stopped
    networks: &networks
      - cloudflare
    depends_on: &depends_on
      - valkey
      - selenium

  accounts-dev:
    <<: *accounts
    container_name: accounts-dev
    profiles: [ "development" ]
    ports:
      - "8080:8080"
    depends_on:
      - valkey-dev

  accounts_hourly:
    <<: *accounts
    restart: no
    profiles: [ "scripts" ]
    container_name: accounts_hourly
    command: "/app/code/accounts/finance_hourly.py"

  valkey: &valkey
    image: valkey/valkey
    container_name: valkey
    networks: *networks
    environment:
      VALKEY_EXTRA_FLAGS: "--save ''"
    volumes:
      - ${HOME}/code/accounts/web/valkey:/data
    user: "1000:1000"
    restart: unless-stopped
  
  valkey-dev:
    <<: *valkey
    profiles: [ "development" ]
    ports:
      - "6379:6379"

  selenium: &selenium
    image: selenium/standalone-chromium
    container_name: selenium
    shm_size: 2g
    environment:
      - SE_ENABLE_TRACING=false
    restart: unless-stopped
    networks: *networks
    ports:
      - "7900:7900"

  selenium-dev:
    <<: *selenium
    container_name: selenium-dev
    profiles: [ "development" ]
    ports:
      - "7901:7900"
      - "4444:4444"

networks:
  cloudflare:
    name: cloudflare
    external: true
