[project]
name = "accounts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fredapi>=0.5.2",
    "joblib>=1.4.2",
    "kaleido==0.2.1",
    "loguru>=0.7.2",
    "nicegui>=2.8.1",
    "numpy-financial>=1.0.0",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "portalocker>=3.0.0",
    "prefixed>=0.9.0",
    "psutil>=6.1.1",
    "pytest-playwright>=0.6.2",
    "retry>=0.9.2",
    "sqlalchemy>=2.0.36",
    "sqlite-utils>=3.38",
    "statsmodels>=0.14.4",
    "yahoofinancials>=1.20",
    "yahooquery>=2.3.7",
    "yfinance>=0.2.50",
]

[tool.uv]
dev-dependencies = [
    "pandas-stubs>=2.2.2.240909",
    "toml>=0.10.2",
]
