[project]
name = "accounts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "amortization>=2.4.0",
    "fredapi>=0.5.2",
    "joblib>=1.4.2",
    "kaleido==0.2.1",
    "loguru>=0.7.2",
    "nicegui>=2.1.0",
    "numpy-financial>=1.0.0",
    "pandas>=2.2.2",
    "plotly>=5.24.0",
    "portalocker>=2.10.1",
    "prefixed>=0.9.0",
    "pytest-playwright>=0.5.2",
    "retry>=0.9.2",
    "sqlalchemy>=2.0.34",
    "sqlite-utils>=3.37",
    "statsmodels>=0.14.2",
    "yahoofinancials>=1.20",
    "yahooquery>=2.3.7",
    "yfinance>=0.2.43",
]

[tool.uv]
dev-dependencies = [
    "pandas-stubs>=2.2.2.240909",
]
