version: '3'

vars:
  HOST: valankar@localhost
  UNISON_CMD: unison -batch -terse
  PROJECT_NAME: accounts
  IMAGE_NAME: '{{.PROJECT_NAME}}'

tasks:
  dev-valkey-restart:
    cmds:
      - docker compose --profile development restart valkey-dev
    sources:
      - ./web/valkey/dump.rdb
  dev-build:
    cmds:
      - docker build -t {{.IMAGE_NAME}} .
      - docker compose --profile development up -d {{.PROJECT_NAME}}-dev
      - docker image prune -f
  prod-push:
    cmds:
      - task: prod-sync
      - ssh {{.HOST}} 'cd code/{{.PROJECT_NAME}} && docker compose up -d && docker image prune -f'
  prod-sync-ledger:
    cmds:
      - >
        {{.UNISON_CMD}} -force {{.LEDGER_DIR}}
        -forcepartial "Path ledger.ledger -> ssh://{{.HOST}}/code/ledger"
        -forcepartial "Path prices.db -> ssh://{{.HOST}}/code/ledger"
        -ignore 'Path __pycache__'
        {{.LEDGER_DIR}} ssh://{{.HOST}}/code/ledger
    vars:
      LEDGER_DIR: '{{.HOME}}/code/ledger'
    status:
      - test -n "$NO_SYNC_LEDGER"
  prod-sync:
    cmds:
      - >
        {{.UNISON_CMD}} -force .
        -forcepartial "BelowPath web -> ssh://{{.HOST}}/code/{{.PROJECT_NAME}}"
        -forcepartial 'Path .schwab_token.json -> newer'
        -ignore 'Path .venv' -ignore 'Path __pycache__' -ignore 'Path .task'
        . ssh://{{.HOST}}/code/{{.PROJECT_NAME}}
      - task: prod-sync-ledger
      - task: dev-valkey-restart
  update-packages:
    cmds:
      - uv lock --upgrade
      - uv sync
      - git diff --quiet uv.lock || git commit uv.lock -m "Update packages"
    generates:
      - uv.lock
  upgrade:
    deps:
      - update-packages
    cmds:
      - task: dev-build
      - task: prod-push
    sources:
      - uv.lock

